-- Tabel Posko
CREATE TABLE IF NOT EXISTS posko (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  status TEXT DEFAULT 'Siaga',
  status_approval TEXT DEFAULT 'pending', -- pending, approved, rejected
  max_capacity INT DEFAULT 100,
  current_load INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Tabel Profil Pengguna (Terhubung ke Supabase Auth)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT DEFAULT 'relawan', -- superadmin, relawan
  posko_id BIGINT REFERENCES posko(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Tabel Pengungsi
CREATE TABLE IF NOT EXISTS pengungsi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  posko_id BIGINT REFERENCES posko(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  age INT NOT NULL,
  gender TEXT NOT NULL,
  status TEXT DEFAULT 'Sehat', -- Sehat, Sakit, Butuh Perawatan
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Tabel Logistik (Inventaris Barang)
CREATE TABLE IF NOT EXISTS logistik (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  posko_id BIGINT REFERENCES posko(id) ON DELETE CASCADE NOT NULL,
  nama TEXT NOT NULL,
  kategori TEXT NOT NULL, -- Pangan, P3K, Sandang, dll
  stok INT DEFAULT 0,
  satuan TEXT NOT NULL, -- kg, dus, pcs
  status TEXT DEFAULT 'Aman', -- Aman, Menipis, Kritis
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Tabel Keuangan (Pemasukan & Pengeluaran)
CREATE TABLE IF NOT EXISTS keuangan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  posko_id BIGINT REFERENCES posko(id) ON DELETE CASCADE NOT NULL,
  tipe TEXT NOT NULL, -- Pemasukan / Pengeluaran
  kategori TEXT NOT NULL, -- Donasi Tunai, Operasional, Logistik, dll
  nominal NUMERIC NOT NULL,
  deskripsi TEXT NOT NULL,
  bukti_url TEXT, -- Link foto/bukti transaksi
  tanggal DATE DEFAULT CURRENT_DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Tabel Siaran (Siaran Informasi/Broadcast)
CREATE TABLE IF NOT EXISTS siaran (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  posko_id BIGINT REFERENCES posko(id) ON DELETE CASCADE, -- NULL jika siaran untuk semua posko
  judul TEXT NOT NULL,
  isi TEXT NOT NULL,
  prioritas TEXT DEFAULT 'Normal', -- Normal / Tinggi
  waktu TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  status TEXT DEFAULT 'Aktif' -- Aktif / Diarsipkan
);

-- Row Level Security (RLS) - Contoh dasar
ALTER TABLE posko ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pengungsi ENABLE ROW LEVEL SECURITY;
ALTER TABLE logistik ENABLE ROW LEVEL SECURITY;
ALTER TABLE keuangan ENABLE ROW LEVEL SECURITY;
ALTER TABLE siaran ENABLE ROW LEVEL SECURITY;

-- Policy dasar (memperbolehkan baca untuk semua user terautentikasi/anonim demi kemudahan portal)
CREATE POLICY "Allow public read posko" ON posko FOR SELECT USING (true);
CREATE POLICY "Allow public read profiles" ON profiles FOR SELECT USING (true);
CREATE POLICY "Allow public read pengungsi" ON pengungsi FOR SELECT USING (true);
CREATE POLICY "Allow public read logistik" ON logistik FOR SELECT USING (true);
CREATE POLICY "Allow public read keuangan" ON keuangan FOR SELECT USING (true);
CREATE POLICY "Allow public read siaran" ON siaran FOR SELECT USING (true);

-- Policy Tulis (Hanya user terautentikasi)
CREATE POLICY "Allow auth insert posko" ON posko FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow auth update posko" ON posko FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow auth all profiles" ON profiles FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow auth all pengungsi" ON pengungsi FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow auth all logistik" ON logistik FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow auth all keuangan" ON keuangan FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow auth all siaran" ON siaran FOR ALL USING (auth.role() = 'authenticated');
